import json
import uuid
import os

# 1. Cấu hình đường dẫn file
COUNTRIES_FILE = 'countries.json'
REGIONS_FILE = 'states.json'
OUTPUT_SQL_FILE = 'import_admin_divisions.sql'

# UUID của tài khoản Admin/System dùng để điền vào created_by
SYSTEM_USER_UUID = '00000000-0000-0000-0000-000000000000'

def escape_sql_string(val):
    """Xử lý ký tự nháy đơn trong SQL (VD: Peoples' Region -> Peoples'' Region)"""
    if val is None:
        return ""
    return str(val).replace("'", "''")

def main():
    # Kiểm tra file tồn tại
    if not os.path.exists(COUNTRIES_FILE) or not os.path.exists(REGIONS_FILE):
        print("❌ Lỗi: Không tìm thấy file countries.json hoặc regions.json")
        return

    print("⏳ Đang đọc dữ liệu JSON...")
    with open(COUNTRIES_FILE, 'r', encoding='utf-8') as f:
        countries = json.load(f)

    with open(REGIONS_FILE, 'r', encoding='utf-8') as f:
        regions = json.load(f)

    # Từ điển ánh xạ từ Country ID (Integer) sang UUID mới tạo
    country_id_to_uuid = {}

    sql_statements = [
        "-- SQL IMPORT SCRIPT GENERATED BY PYTHON",
        "-- Bật transaction để đảm bảo an toàn dữ liệu (lỗi là rollback hết)",
        "BEGIN;\n"
    ]

    print("⏳ Đang xử lý dữ liệu Quốc gia (Level: country)...")
    for country in countries:
        c_uuid = str(uuid.uuid4())
        country_id_to_uuid[country['id']] = c_uuid

        name = escape_sql_string(country.get('name', ''))
        
        # Gom các trường thừa vào metadata
        metadata = {
            "iso2": country.get('iso2'),
            "iso3": country.get('iso3'),
            "phonecode": country.get('phonecode'),
            "capital": country.get('capital'),
            "currency": country.get('currency'),
            "native": country.get('native'),
            "emoji": country.get('emoji'),
            "flag": country.get('flag')
        }
        # Loại bỏ các trường có giá trị None cho sạch JSON
        metadata = {k: v for k, v in metadata.items() if v is not None}
        metadata_json = escape_sql_string(json.dumps(metadata, ensure_ascii=False))

        sql = (
            f"INSERT INTO administrative_divisions "
            f"(id, parent_id, level, name, metadata, status, created_by) "
            f"VALUES ('{c_uuid}', NULL, 'country', '{name}', '{metadata_json}'::jsonb, 'active', '{SYSTEM_USER_UUID}');"
        )
        sql_statements.append(sql)

    sql_statements.append("\n-- ==========================================\n")

    print("⏳ Đang xử lý dữ liệu Khu vực/Tỉnh thành (Level: province)...")
    for region in regions:
        r_uuid = str(uuid.uuid4())
        country_id = region.get('country_id')
        
        # Lấy UUID của quốc gia cha
        parent_uuid = country_id_to_uuid.get(country_id)
        if not parent_uuid:
            # Nếu không tìm thấy quốc gia cha thì để NULL hoặc bỏ qua tùy logic của bạn
            parent_id_sql = "NULL"
        else:
            parent_id_sql = f"'{parent_uuid}'"

        name = escape_sql_string(region.get('name', ''))
        
        # Xác định level (nếu type là null thì mặc định là 'province')
        level_val = region.get('type')
        level = level_val.lower() if level_val else 'province'

        # Gom các trường thừa vào metadata
        metadata = {
            "country_code": region.get('country_code'),
            "iso2": region.get('iso2'),
            "type": region.get('type'),
            "latitude": region.get('latitude'),
            "longitude": region.get('longitude')
        }
        metadata = {k: v for k, v in metadata.items() if v is not None}
        metadata_json = escape_sql_string(json.dumps(metadata, ensure_ascii=False))

        sql = (
            f"INSERT INTO administrative_divisions "
            f"(id, parent_id, level, name, metadata, status, created_by) "
            f"VALUES ('{r_uuid}', {parent_id_sql}, '{level}', '{name}', '{metadata_json}'::jsonb, 'active', '{SYSTEM_USER_UUID}');"
        )
        sql_statements.append(sql)

    sql_statements.append("\nCOMMIT;")

    # Ghi ra file SQL
    print(f"⏳ Đang ghi ra file {OUTPUT_SQL_FILE}...")
    with open(OUTPUT_SQL_FILE, 'w', encoding='utf-8') as f:
        f.write("\n".join(sql_statements))

    print(f"✅ Hoàn thành! Đã tạo file '{OUTPUT_SQL_FILE}' với {len(countries) + len(regions)} dòng dữ liệu.")

if __name__ == '__main__':
    main()